import os
import sys
import requests
from github import Github, Auth

OPENROUTER_MODEL = "google/gemini-2.0-flash-001"

SYSTEM_PROMPT = """
# Role & Objective
You are an expert Senior Software Engineer and Technical Auditor. Your task is to review the content of a GitHub Pull Request (PR). You must evaluate the code quality, practical value, and origin of the code based on the specific criteria listed below.

# Evaluation Criteria

1.  **Summary of Changes**: Briefly summarize what this PR does (e.g., bug fix, new feature, refactoring).
2.  **AI-Generated Content Analysis**: Estimate the likelihood and percentage of the code being generated by AI. Analyze patterns such as generic variable naming, over-commenting, specific boilerplate styles, or lack of domain-specific nuance.
3.  **Engineering Reality Check**: specific analysis of whether this addresses a realistic, production-grade engineering problem. Does it handle edge cases? Is it merely a "toy example" or does it close the gap to real-world application?
4.  **Economic Value**: Assess the potential economic impact. Does it reduce technical debt, improve performance, enable revenue-generating features, or optimize costs?
5.  **Verification & Testing**: Check for the presence and quality of verification procedures (unit tests, integration tests, CI pipelines). Are the changes verifiable?
6.  **Documentation Quality**: Evaluate the presence of guiding documentation (README updates, docstrings, usage guides). Is it easy for a new developer to understand?
7.  **Organizational Structure**: Analyze the project structure. Is the file organization logical, modular, and scalable?

# Output Format Rules

1.  **Dual Language Output**: You MUST provide the full response in **English first**, followed immediately by a **Chinese translation**.
2.  **Structure**: Use Markdown headers for each section.
3.  **Tone**: Professional, critical, and objective.

# Response Template

## 🇬🇧 English Analysis

### 1. Executive Summary
[Brief summary here]

### 2. AI Content Analysis
* **Estimated AI Component**: [0-100%]
* **Reasoning**: [Analysis of code patterns, logic density, etc.]

### 3. Engineering & Economic Assessment
* **Engineering Gap**: [Analyze if this is a realistic engineering problem vs. theoretical/toy code]
* **Economic Value**: [High/Medium/Low - Explanation of business impact]

### 4. Quality Assurance
* **Verification**: [Analysis of tests and validation steps]
* **Documentation**: [Analysis of guides and docs]
* **Organization**: [Analysis of structure and modularity]

---

## 🇨🇳 中文分析

### 1. 摘要
[此处为摘要]

### 2. AI 成分分析
* **预估 AI 含量**: [0-100%]
* **判断依据**: [分析代码模式、逻辑密度等]

### 3. 工程与经济评估
* **工程现实差距**: [分析是解决实际工程问题还是仅为理论/玩具代码]
* **经济价值**: [高/中/低 - 说明商业影响]

### 4. 质量保证
* **验证程序**: [分析测试和验证步骤]
* **文档质量**: [分析引导文档]
* **组织结构**: [分析代码结构和模块化]

---

**Please adhere to these rules and analyze the following PR content:**
[PASTE PR CONTENT/DIFF HERE]
"""
# ===========================================

def get_pr_diff(repo, pr_number):
    pr = repo.get_pull(pr_number)
    
    headers = {
        'Authorization': f'token {os.getenv("GITHUB_TOKEN")}',
        'Accept': 'application/vnd.github.v3.diff' 
    }
    
    response = requests.get(pr.url, headers=headers)
    response.raise_for_status()
    return response.text

def analyze_code_with_llm(diff_content):
    """通过 OpenRouter 调用 LLM"""
    api_key = os.getenv("LLM_API_KEY")
    if not api_key:
        return "❌ 无法进行审查：未配置 LLM_API_KEY。"

    # OpenRouter
    url = "https://openrouter.ai/api/v1/chat/completions"
    
    # 截断 Diff 以防止超长 (OpenRouter 部分模型支持 1M+ context，但为了省钱还是截断一下)
    # Gemini Flash 支持 1M context，这里可以设置得很大
    max_len = 32000 
    truncated_diff = diff_content[:max_len] + ("\n...(diff truncated due to length)" if len(diff_content) > max_len else "")

    payload = {
        "model": OPENROUTER_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"The following is the Diff content of the PR: \n\n```diff\n{truncated_diff}\n```"}
        ],
        # OpenRouter 特定参数
        "temperature": 0.2,
        "top_p": 0.9,
    }
    
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}",
        "HTTP-Referer": "https://github.com/my-repo-agent", 
        "X-Title": "GitHub PR Review Agent"
    }

    try:
        response = requests.post(url, headers=headers, json=payload, timeout=120)
        
        if response.status_code != 200:
            print(f"DEBUG: OpenRouter Error Status: {response.status_code}")
            print(f"DEBUG: OpenRouter Response: {response.text}")
            response.raise_for_status()

        result = response.json()
        
        content = result['choices'][0]['message'].get('content')
        if not content:
            return "❌ AI 返回了空内容，请检查 OpenRouter 日志。"
            
        return content

    except Exception as e:
        return f"🤖 LLM 调用失败: {str(e)}"

def main():
    github_token = os.getenv("GITHUB_TOKEN")
    repo_name = os.getenv("GITHUB_REPOSITORY") 
    pr_number = os.getenv("PR_NUMBER")

    if not all([github_token, repo_name, pr_number]):
        print("Missing environment variables (GITHUB_TOKEN, GITHUB_REPOSITORY, PR_NUMBER).")
        sys.exit(1)

    try:
        auth = Auth.Token(github_token)
        g = Github(auth=auth)
        
        repo = g.get_repo(repo_name)
        pr = repo.get_pull(int(pr_number))

        print(f"🚀 开始审查 PR #{pr_number} : {pr.title} ...")

        try:
            diff_text = get_pr_diff(repo, int(pr_number))
        except Exception as e:
            print(f"❌ 获取 Diff 失败: {e}")
            sys.exit(1)
        
        if not diff_text.strip():
            print("⚠️ Diff 为空，跳过审查。")
            return

        print(f"📄 Diff 获取成功 (长度: {len(diff_text)} chars)，正在发送给 OpenRouter ({OPENROUTER_MODEL})...")

        review_comment = analyze_code_with_llm(diff_text)
        
        print(f"✅ 审查完成，准备提交评论...")
        
        final_comment = f"## 🤖 AI Code Review ({OPENROUTER_MODEL})\n\n{review_comment}"
        
        pr.create_issue_comment(final_comment)
        print("🎉 评论已发布到 GitHub。")

    except Exception as e:
        print(f"❌ 发生未捕获错误: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()